# Generated by Django 3.2.4 on 2021-11-14 05:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('collaps_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('patient_help', models.BooleanField(default=False)),
                ('doctor_help', models.BooleanField(default=False)),
                ('laboratory_help', models.BooleanField(default=False)),
                ('pharmacy_help', models.BooleanField(default=False)),
                ('assistant_help', models.BooleanField(default=False)),
                ('ordering', models.IntegerField()),
            ],
            options={
                'order_with_respect_to': 'ordering',
            },
        ),
    ]
